#!/usr/bin/env ansible-playbook
---

# Debian & Ubuntu
#################

- name: "==> Setting php-fpm on Debian system"
  include_tasks: php-fpm-ubuntu.yml
  when: ansible_pkg_mgr == "apt"

# CentOS
########

- name: "==> Setting php-fpm on RHEL system"
  include_tasks: php-fpm-centos.yml
  when: ansible_pkg_mgr == "yum"

# vim: ft=yaml.ansible :
