#!/usr/bin/env ansible-playbook
---

- name: Check php-fpm process
  shell: >
    set -o pipefail && \
    ps -A | grep php-fpm
  register: php_process
  args:
    executable: /bin/bash
  changed_when: false

- name: Print php-fpm process
  debug:
    msg: "{{ php_process.stdout_lines }}"

# vim: ft=yaml.ansible :
